
camunda.bpm.admin-user:
  id: demo
  password: demo

spring.h2.console:
  enabled: true
  path: /h2-console
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delay_items_demo
    username: root
    password: 29121998
    driver-class-name: com.mysql.jdbc.Driver